import Head from 'next/head'
import React from "react"
//import TodoComponent from "../src/TodoComponent.bs" 
import Header from "../src/Header.bs"
import InputTodo from "../src/InputTodo.bs"
import TodoItem from "../src/TodoItem.bs"


export default function TodoComponent() {
  return (   
    <>
      <Head />
        <title>Next.js TODO APP</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>  
      <div>
      <main>
        <div id="__next">
        <React.StrictMode>
          <TodoComponent />
          <div className="container">
                <div className="inner">
                  <Header />
                  <InputTodo />
                  <TodoItem 
                   
                  />
                </div>
              </div>
        </React.StrictMode>
        </div>
      </main>
      </div>
    </>
  )}
