
import Head from 'next/head'
import React from "react"
import Todos from "../src/Todos.bs"


export default function App() {
  return (   
    <>
      <Head />
        <title>Next.js TODO APP</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>  
      <div>
      <main>
        <div id="__next">
        <React.StrictMode>
          <Todos />
 
        </React.StrictMode>
        </div>
      </main>
      </div>
    </>
  )}
