// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Header$default(Props) {
  var headerStyle = {
    lineHeight: "1.5em",
    padding: "20px 0"
  };
  return React.createElement(React.Fragment, undefined, React.createElement("header", {
                  style: headerStyle
                }, React.createElement("h1", {
                      style: {
                        color: "#ececec",
                        fontSize: "6rem",
                        fontWeight: "600",
                        lineHeight: "1em",
                        marginBottom: "2rem",
                        textAlign: "center",
                        textTransform: "lowercase"
                      }
                    }, "todos")));
}

var $$default = Header$default;

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
