// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as TodoComponent from "./TodoComponent.bs.js";
import * as Fa from "react-icons/fa";

var FaPlusCircle = {};

function InputTodo(Props) {
  var match = React.useReducer(TodoComponent.reducer, TodoComponent.initialState);
  var dispatch = match[1];
  var onChange = function (e) {
    var value = e.target.value;
    Curry._1(dispatch, {
          TAG: /* InputChange */0,
          _0: value
        });
  };
  var handleSubmit = function (e) {
    e.preventDefault();
  };
  return React.createElement(React.Fragment, undefined, React.createElement("form", {
                  className: "form-container",
                  onSubmit: handleSubmit
                }, React.createElement("input", {
                      className: "input-text",
                      placeholder: "Add todo...",
                      type: "text",
                      value: match[0].inputValue,
                      onChange: onChange
                    }), React.createElement("button", {
                      className: "input-submit",
                      onClick: (function (param) {
                          Curry._1(dispatch, /* AddTodo */0);
                        })
                    }, React.createElement(Fa.FaPlusCircle, {}))));
}

var make = InputTodo;

export {
  FaPlusCircle ,
  make ,
}
/* react Not a pure module */
