// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Fa from "react-icons/fa";
import * as TodoItemModuleCss from "../styles/TodoItem.module.css";

var styles = TodoItemModuleCss;

var FaTrash = {};

function TodoItem(Props) {
  var todo = Props.todo;
  var dispatch = Props.dispatch;
  var i = Props.i;
  var content = todo.content;
  var match = React.useState(function () {
        return content;
      });
  var setValue = match[1];
  var value = match[0];
  var handleUpdate = function (param) {
    Curry._1(dispatch, {
          TAG: /* SetUpdate */1,
          value: value,
          i: i
        });
  };
  var handleDelete = function (param) {
    Curry._1(dispatch, /* ClearTodos */1);
  };
  var handleCancel = function (param) {
    Curry._1(dispatch, {
          TAG: /* Toggle */2,
          _0: i
        });
    Curry._1(setValue, (function (param) {
            return content;
          }));
  };
  var handleInput = function (e) {
    var value = e.target.value;
    Curry._1(dispatch, {
          TAG: /* InputChange */0,
          _0: value
        });
  };
  return React.createElement("li", {
              className: styles.item
            }, todo.isDone ? React.createElement(React.Fragment, undefined, React.createElement("div", {
                        onDoubleClick: handleUpdate
                      }, React.createElement("input", {
                            className: styles.textInput,
                            type: "text",
                            value: content,
                            onKeyDown: handleDelete,
                            onChange: handleInput
                          }), React.createElement("button", {
                            onClick: handleCancel
                          }, React.createElement(Fa.FaTrash, {})))) : React.createElement(React.Fragment, undefined, React.createElement("div", {
                        onDoubleClick: handleUpdate
                      }, React.createElement("input", {
                            className: styles.completedStyle,
                            type: "text",
                            value: content,
                            onKeyDown: handleDelete,
                            onChange: handleInput
                          }), React.createElement("button", {
                            onClick: handleCancel
                          }, React.createElement(Fa.FaTrash, {})))));
}

var make = TodoItem;

export {
  styles ,
  FaTrash ,
  make ,
}
/* styles Not a pure module */
