// Generated by ReScript, PLEASE EDIT WITH CARE


var initialState_todoList = [];

var initialState = {
  todoList: initialState_todoList,
  inputValue: ""
};

function reducer(state, action) {
  if (typeof action === "number") {
    if (action === /* AddTodo */0) {
      return {
              todoList: state.todoList.concat([{
                      content: state.inputValue,
                      isDone: false
                    }]),
              inputValue: ""
            };
    } else {
      return {
              todoList: [],
              inputValue: state.inputValue
            };
    }
  }
  switch (action.TAG | 0) {
    case /* InputChange */0 :
        return {
                todoList: state.todoList,
                inputValue: action._0
              };
    case /* SetUpdate */1 :
        var i = action.i;
        var value = action.value;
        return {
                todoList: state.todoList.map(function (todo, index) {
                      if (i === index) {
                        return {
                                content: value,
                                isDone: false
                              };
                      } else {
                        return todo;
                      }
                    }),
                inputValue: state.inputValue
              };
    case /* Toggle */2 :
        var i$1 = action._0;
        return {
                todoList: state.todoList.map(function (e, index) {
                      var isDone = i$1 === index ? !e.isDone : false;
                      return {
                              content: e.content,
                              isDone: isDone
                            };
                    }),
                inputValue: state.inputValue
              };
    
  }
}

export {
  initialState ,
  reducer ,
}
/* No side effect */
